### ISSUE TITLE
What happened to your xA-Scraper project?

### ISSUE THREAD

**Issue by ylluminarious** [fake-name/ReadableWebProxy#521]
Hi,

Sorry, this isn't exactly an appropriate place to ask this, but I can't find your email address anywhere so this is the only recourse I have. I was going to start using your [xA-Scraper project](https://github.com/fake-name/xA-Scraper) to archive some Patreon posts from one of my supported content creators. I actually discussed this with you in a ticket I filed over there and you even made some improvements to the program. But, just today, I discovered xA-Scraper is totally gone. I know you deleted your even older Patreon-Archiver project, but now you've deleted xA-Scraper too? Was it incorporated into this project? Please help me out here, as this deletion of repostitories is more than a little jarring.

Thanks.

**Comment by fake-name** [comment]
I'm in the process of changing jobs, so I cleaned up some of the more explicitly *adult-oriented* projects. 

FWIW, **someone** just *happens* to be hosting a mirror over [here](https://github.com/herp-a-derp/xA-Scraper).

**Comment by ylluminarious** [comment]
@fake-name Ah, I understand. That's kind of funny, I didn't think of your project(s) as being adult-oriented since the person I'm supporting on Patreon is actually a scientific researcher  :sweat_smile:

Thanks for linking me to the mirror. I see that the history is totally collapsed, but other than that does it appear to be up-to-date?

Thanks again, I really appreciate your help here.

**Comment by fake-name** [comment]
It's identical to the current HEAD of my private git repo where I've moved things.

**Comment by ylluminarious** [comment]
@fake-name Fantastic! Thanks so much, that's great to know. Would you mind giving me access to that private git repo so that I can more easily track down bugs and possibly even make improvements? I would not share it publicly anywhere without your specific permission.

> Please tell me it isn't Jordan Peterson.

Lol, is he even a scientific researcher? I thought he was more of a political commentator. But, no, the person I support is a physicist / engineer trying to answer some questions about quantum mechanics.

**Comment by fake-name** [comment]
> Lol, is he even a scientific researcher? I thought he was more of a political commentator. 

This is accurate, but if you listen to his fans BuT tHe 
CoNTeXTBLARGHBLEGARBLEGASJ lobsters KFLASKJDHFGSLKJDGS.

Really, he's more of a "let's see if I can come up with a bullshit answer to support my preexisting conclusion" wacko.

Anyways, I still plan to maintain the project. Feel free to file issues on the new repo.

**Comment by ylluminarious** [comment]
> This is accurate, but if you listen to his fans BuT tHe
CoNTeXTBLARGHBLEGARBLEGASJ lobsters KFLASKJDHFGSLKJDGS.
>
> Really, he's more of a "let's see if I can come up with a bullshit answer to support my preexisting conclusion" wacko.

Hmm, I see.

> Anyways, I still plan to maintain the project. Feel free to file issues on the new repo.

You mean the mirror? Do you actually have access to that mirror or are you planning to fork it, etc.?

**Comment by Aidolii** [comment]
![](https://i.imgur.com/fgyQEln.png)

**Comment by fake-name** [comment]
So lightend. Very light.

**Comment by Aidolii** [comment]
I'm a bit concerned the new maintainer of the project doesn't have email notifications enabled.

**Comment by fake-name** [comment]
I'm pretty sure everything is still around [over here](https://github.com/herp-a-derp/). 

Also, git commits are literally driven by e-mail accounts. If you clone a repo, every single commit has a e-mail address attached. I think github doesn't expose them via HTML probably to prevent scrapers from finding them.
